#ifndef  OPTIONS_DEFINED
#define  OPTIONS_DEFINED

#ifndef  NUM_INITIAL_ATOMS
#define  NUM_INITIAL_ATOMS 4096
#endif /*NUM_INITIAL_ATOMS*/

#ifndef  BUFFER_MAX_SIZE
#define  BUFFER_MAX_SIZE 256
#endif /*BUFFER_MAX_SIZE*/

#ifndef  CHAR_POOL_SIZE
#define  CHAR_POOL_SIZE 32768
#endif /*CHAR_POOL_SIZE*/

#ifndef  NUM_INITIAL_STRINGS
#define  NUM_INITIAL_STRINGS 1024
#endif /*NUM_INITIAL_STRINGS*/

#endif /*OPTIONS_DEFINED*/
